databases:
  - name: db
    databaseName: extaber
    user: admin
    plan: free
    ipAllowList: [] # only allow internal connections

services:
  - type: web
    name: api
    repo: https://github.com/sven-gerlach/extaber-api.git
    env: python
    region: ohio
    plan: free
    branch: main
    buildCommand: pipenv install --deploy --system && python manage.py migrate --no-input
    startCommand: gunicorn -b :$PORT extaber-api:wsgi
    envVars:
      - key: CLIENT_ORIGIN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
      - key: POSTGRES_PASSWORD
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DOPPLER_CONFIG
        sync: false