# Generated by Django 3.0 on 2021-04-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210415_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
