# Generated by Django 3.0 on 2021-04-16 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210415_1327'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentvote',
            unique_together={('owner', 'comment')},
        ),
    ]
