# Generated by Django 3.0 on 2021-04-14 03:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210413_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='owner',
            new_name='owner_id',
        ),
        migrations.RemoveField(
            model_name='article',
            name='owner',
        ),
        migrations.CreateModel(
            name='ArticleVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)])),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Article')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='_article_votes_+', through='api.ArticleVotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
