# Generated by Django 3.0 on 2021-04-14 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210414_0347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlevotes',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='articlevotes',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
