# Generated by Django 3.0 on 2021-04-16 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210416_1823'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentvote',
            unique_together=set(),
        ),
    ]
