# Generated by Django 3.0 on 2021-04-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210416_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_img_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
