# Generated by Django 3.0 on 2021-04-14 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_article_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleVotes',
            new_name='ArticleVote',
        ),
    ]
