# Generated by Django 3.0 on 2021-04-14 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210414_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='votes', through='api.ArticleVote', to=settings.AUTH_USER_MODEL),
        ),
    ]
